package com.donHub.donHub.model;

public enum Category {
	
	EDUCATIONAL_MATERIALS,
	ELECTRONICS,
	FURNITURE_AND_HOME,
	ESSENTIALS,
	CLOTHING_AND_ACCESSORIES,
	TRANSPORTATION,
	MUSICALINSTRUMENTS,
	FREEBIES,
	DIYS,
	MISCELLANEOUS,
	HEALTH,
	ENTERTAINMENT
	}
